### ISSUE TITLE
How to train and evaluate algorithms on the robot_env?

### ISSUE THREAD

**Issue by Bxliang868** [SuReLI/SGQN#6]
1) I follow the scripts file to train the algorithms, but I want to known where is the use of the train_new.py ?
2) When I use the eval.py to evaluate the algorithms, there are some problems: 
Traceback (most recent call last):
  File "src/eval.py", line 117, in <module>
    main(args)
  File "src/eval.py", line 55, in main
    action_repeat=args.action_repeat,
AttributeError: 'Namespace' object has no attribute 'action_repeat'
I find this eval.py  is same to the \DMC\src\eval.py, but it's obvious that these two issues are different.

**Comment by DavidBert** [comment]
Hey! 
Sorry these two files should not be included in the public repo, its a mistake.
The ```train_new.py``` file was just a sand bow we used to get random pictures of the environment. If you look closely it's not a training loop but just a script that performs a random trajectory and save an image of the last state.
The eval file is just a plain copy of the one in ```\DMC``` without any modification. It is just a remnant files that should not be present in this folder. If you want an equivalent  ```evaluate.py```file for the robot_env you should take inspiration from the one in ```\DMC```and modify the ```evaluate```method to match with the one implemented [here](https://github.com/SuReLI/SGQN/blob/96ddeb9dec0740a7f96c49b6c9f956d80b90066d/robot_env/src/train.py#L15).
Sorry for this oversight on our part to delete these files. It's now done, thank you for pointing this out to us.

**Comment by Bxliang868** [comment]
Thanks for your replay! 
The appendix D provides additional results on a vision-based robotic environment:" We modified the original simulator to include three testing environments for both tasks......". The "Test 1-3"is equivalent to the Robotic Manipulation introduced by
(Jangir et al. 2022) ? Can I adopt four test environments  "Test 1-4" for each task?

**Comment by DavidBert** [comment]
It's been a while since I did not interacted  with it but yes I think so.
